pygments_style github-dark

foreground #e0def4
background #232136

title_fg #e0def4
title_bg #232136

margin_bg #232136
margin_fg #6e6a86

hunk_margin_bg  #2a273f
hunk_bg         #393552
filler_bg       #2a283e

removed_bg      #2a283e
added_bg        #2a283e

removed_margin_bg       #44415a
added_margin_bg         #44415a

highlight_removed_bg    #420712
highlight_added_bg      #074a2a

search_bg #f6c177
search_fg #232136
select_bg #393552
select_fg #ea9a97
