## name: Rosé Pine Moon (Refined)
## author: mvllow
## refined-by: pseudoc
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine-moon.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground               #e0def4
background               #232136
selection_foreground     #e0def4
selection_background     #44415a

cursor                   #56526e
cursor_text_color        #e0def4

url_color                #c4a7e7

active_tab_foreground    #e0def4
active_tab_background    #393552
inactive_tab_foreground  #6e6a86
inactive_tab_background  #232136

active_border_color      #3e8fb0
inactive_border_color    #44415a

# black
color0   #232136
color8   #393552

# red
color1   #eb6f92
color9   #ffa4c6

# green
color2   #3e8fb0
color10  #73c4e4

# yellow
color3   #f6c177
color11  #fff6ab

# blue
color4   #9ccfd8
color12  #d1ffff

# magenta
color5   #c4a7e7
color13  #f9dcff

# cyan
color6   #ea9a97
color14  #ffcfcb

# white
color7   #e0def4
color15  #ffffff
